In [1]:
#Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
# Set path

path = r'C:\Users\Josh Wattay\OneDrive\Documents\Desktop\Flight Delay Analysis - Raw Data\2020'

In [3]:
# Import Datasets

df = pd.read_csv(os.path.join(path, 'flights2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9136\81471578.py:3: DtypeWarning: Columns (11,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, 'flights2020.csv'), index_col = False)

In [5]:
#Shape Check
df.shape

(5022397, 70)

In [6]:
# Set the display option to show all 70 columns
pd.set_option('display.max_columns', 70)

In [7]:
#Inspect Dataframe and begin Cleaning by ensuring columns are named appropriately
df.head()

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,IATA_Code_Originally_Scheduled_Code_Share_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivDistance,Duplicate
0,0,2020,1,1,17,5,2020-01-17,B6,20409,B6,942,NaN,B6,20409,B6,N661JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,15.0,1941.0,2212.0,6.0,2229,2218.0,-11.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,172.0,151.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,1,2020,1,1,18,6,2020-01-18,B6,20409,B6,942,NaN,B6,20409,B6,N584JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,14.0,1940.0,2207.0,13.0,2229,2220.0,-9.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,174.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,2,2020,1,1,19,7,2020-01-19,B6,20409,B6,942,NaN,B6,20409,B6,N662JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1947.0,7.0,7.0,0.0,0.0,1900-1959,11.0,1958.0,2217.0,6.0,2229,2223.0,-6.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,156.0,139.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,3,2020,1,1,20,1,2020-01-20,B6,20409,B6,942,NaN,B6,20409,B6,N784JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1933.0,-7.0,0.0,0.0,-1.0,1900-1959,27.0,2000.0,2220.0,13.0,2229,2233.0,4.0,4.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,180.0,140.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,4,2020,1,1,21,2,2020-01-21,B6,20409,B6,942,NaN,B6,20409,B6,N784JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1952.0,12.0,12.0,0.0,0.0,1900-1959,10.0,2002.0,2229.0,6.0,2229,2235.0,6.0,6.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,163.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

The 'Unnamed: 0' column will be removed as it is an additional index and redundant.

In [8]:
# Drop the 'Unnamed: 0' column
df = df.drop(columns=['Unnamed: 0'])

In [9]:
df.shape

(5022397, 69)

In [10]:
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,IATA_Code_Originally_Scheduled_Code_Share_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivDistance,Duplicate
0,2020,1,1,17,5,2020-01-17,B6,20409,B6,942,NaN,B6,20409,B6,N661JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,15.0,1941.0,2212.0,6.0,2229,2218.0,-11.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,172.0,151.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,2020,1,1,18,6,2020-01-18,B6,20409,B6,942,NaN,B6,20409,B6,N584JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,14.0,1940.0,2207.0,13.0,2229,2220.0,-9.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,174.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,2020,1,1,19,7,2020-01-19,B6,20409,B6,942,NaN,B6,20409,B6,N662JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1947.0,7.0,7.0,0.0,0.0,1900-1959,11.0,1958.0,2217.0,6.0,2229,2223.0,-6.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,156.0,139.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,2020,1,1,20,1,2020-01-20,B6,20409,B6,942,NaN,B6,20409,B6,N784JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1933.0,-7.0,0.0,0.0,-1.0,1900-1959,27.0,2000.0,2220.0,13.0,2229,2233.0,4.0,4.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,180.0,140.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,2020,1,1,21,2,2020-01-21,B6,20409,B6,942,NaN,B6,20409,B6,N784JB,942,14027,1402702,34027,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,1052906,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1952.0,12.0,12.0,0.0,0.0,1900-1959,10.0,2002.0,2229.0,6.0,2229,2235.0,6.0,6.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,163.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

Rename syntax for various columns for consistency and accuracy.

In [11]:
# Define the dictionary for renaming columns
rename_dict = {
    'DayofMonth': 'Day_of_Month',
    'DayOfWeek': 'Day_of_Week',
    'FlightDate': 'Flight_Date',
    'Operating_Airline': 'Operating Airline',
    'OriginAirportID': 'Origin_Airport_ID',
    'OriginAirportSeqID': 'Origin_Airport_Seq_ID',
    'OriginCityMarketID': 'Origin_City_Market_ID',
    'OriginCityName': 'Origin_City_Name',
    'OriginState': 'Origin_State',
    'OriginStateFips': 'Origin_State_Fips',
    'OriginStateName': 'Origin_State_Name',
    'DestAirportID': 'Dest_Airport_ID',
    'DestAirportSeqID': 'Dest_Airport_Seq_ID',
    'DestCityMarketID': 'Dest_City_Market_ID',
    'DestCityName': 'Dest_City_Name',
    'DestState': 'Dest_State',
    'DestStateFips': 'Dest_State_Fips',
    'DestStateName': 'Dest_State_Name',
    'CRSDepTime': 'CRS_Dep_Time',
    'DepTime': 'Dep_Time',
    'DepDelay': 'Dep_Delay',
    'DepDelayMinutes': 'Dep_Delay_Minutes',
    'DepDel15': 'Dep_Del_15',
    'DepartureDelayGroups': 'Departure_Delay_Groups',
    'DepTimeBlk': 'Dep_Time_Blk',
    'TaxiOut': 'Taxi_Out',
    'WheelsOff': 'Wheels_Off',
    'WheelsOn': 'Wheels_On',
    'TaxiIn': 'Taxi_In',
    'CRSArrTime': 'CRS_Arr_Time',
    'ArrTime': 'Arr_Time',
    'ArrDelay': 'Arr_Delay',
    'ArrDelayMinutes': 'Arr_Delay_Minutes',
    'ArrDel15': 'Arr_Del_15',
    'ArrivalDelayGroups': 'Arrival_Delay_Groups',
    'ArrTimeBlk': 'Arr_Time_Blk',
    'CancellationCode': 'Cancellation_Code',
    'CRSElapsedTime': 'CRS_Elapsed_Time',
    'ActualElapsedTime': 'Actual_Elapsed_Time',
    'AirTime': 'Air_Time',
    'DistanceGroup': 'Distance_Group',
    'CarrierDelay': 'Carrier_Delay',
    'WeatherDelay': 'Weather_Delay',
    'NASDelay': 'NAS_Delay',
    'SecurityDelay': 'Security_Delay',
    'LateAircraftDelay': 'Late_Aircraft_Delay',
    'FirstDepTime': 'First_Dep_Time',
    'TotalAddGTime': 'Total_Add_G_Time',
    'LongestAddGTime': 'Longest_Add_G_Time',
    'DivDistance': 'Div_Distance'
}

# Rename the columns
df = df.rename(columns=rename_dict)

In [12]:
df.shape

(5022397, 69)

In [13]:
# Drop the additional irrelevant columns - please refer to the 'Cleaning 2019 Flight Data' script for more details.

df = df.drop(columns=['First_Dep_Time', 'Total_Add_G_Time', 'Longest_Add_G_Time', 'Div_Distance'])

Fortunately, this raw data comes with a Duplicate flag column.
I will check the counts for this column to check for any values of 'Y' or Yes.
To be certain, I will also run a duplicate check with the .duplicated command.

In [14]:
df['Duplicate'].value_counts()

Duplicate
N    5022397
Name: count, dtype: int64

In [15]:
# So far so good, now to check for duplicates in the entire dataframe by creating a subset of duplicated rows

# Create a DataFrame containing only the duplicate rows
dups = df[df.duplicated(keep=False)]

# Display the 'dups' DataFrame
print(dups)

Empty DataFrame
Columns: [Year, Quarter, Month, Day_of_Month, Day_of_Week, Flight_Date, Marketing_Airline_Network, DOT_ID_Marketing_Airline, IATA_Code_Marketing_Airline, Flight_Number_Marketing_Airline, IATA_Code_Originally_Scheduled_Code_Share_Airline, Operating_Airline , DOT_ID_Operating_Airline, IATA_Code_Operating_Airline, Tail_Number, Flight_Number_Operating_Airline, Origin_Airport_ID, Origin_Airport_Seq_ID, Origin_City_Market_ID, Origin, Origin_City_Name, Origin_State, Origin_State_Fips, Origin_State_Name, Dest_Airport_ID, Dest_Airport_Seq_ID, Dest_City_Market_ID, Dest, Dest_City_Name, Dest_State, Dest_State_Fips, Dest_State_Name, CRS_Dep_Time, Dep_Time, Dep_Delay, Dep_Delay_Minutes, Dep_Del_15, Departure_Delay_Groups, Dep_Time_Blk, Taxi_Out, Wheels_Off, Wheels_On, Taxi_In, CRS_Arr_Time, Arr_Time, Arr_Delay, Arr_Delay_Minutes, Arr_Del_15, Arrival_Delay_Groups, Arr_Time_Blk, Cancelled, Cancellation_Code, Diverted, CRS_Elapsed_Time, Actual_Elapsed_Time, Air_Time, Flights, Distance, Distance_Group, Carrier_Delay, Weather_Delay, NAS_Delay, Security_Delay, Late_Aircraft_Delay, Duplicate]
Index: []

In [16]:
# No dups!

Now I will address missing and/or null values.

In [18]:
# Set the display option to show all rows
pd.set_option('display.max_rows', None)

In [19]:
# Find the count of null values in each column
null_counts = df.isnull().sum()

In [20]:
# Display the count of null values
print(null_counts)

Year                                                       0
Quarter                                                    0
Month                                                      0
Day_of_Month                                               0
Day_of_Week                                                0
Flight_Date                                                0
Marketing_Airline_Network                                  0
DOT_ID_Marketing_Airline                                   0
IATA_Code_Marketing_Airline                                0
Flight_Number_Marketing_Airline                            0
IATA_Code_Originally_Scheduled_Code_Share_Airline    5021838
Operating_Airline                                          0
DOT_ID_Operating_Airline                                   0
IATA_Code_Operating_Airline                                0
Tail_Number                                           168453
Flight_Number_Operating_Airline                            0
Origin_Airport_ID                                          0
Origin_Airport_Seq_ID                                      0
Origin_City_Market_ID                                      0
Origin                                                     0
Origin_City_Name                                           0
Origin_State                                               0
Origin_State_Fips                                          0
Origin_State_Name                                          0
Dest_Airport_ID                                            0
Dest_Airport_Seq_ID                                        0
Dest_City_Market_ID                                        0
Dest                                                       0
Dest_City_Name                                             0
Dest_State                                                 0
Dest_State_Fips                                            0
Dest_State_Name                                            0
CRS_Dep_Time                                               0
Dep_Time                                              299620
Dep_Delay                                             299683
Dep_Delay_Minutes                                     299683
Dep_Del_15                                            299683
Departure_Delay_Groups                                299683
Dep_Time_Blk                                               0
Taxi_Out                                              300426
Wheels_Off                                            300426
Wheels_On                                             302000
Taxi_In                                               302000
CRS_Arr_Time                                               0
Arr_Time                                              301999
Arr_Delay                                             309467
Arr_Delay_Minutes                                     309467
Arr_Del_15                                            309467
Arrival_Delay_Groups                                  309467
Arr_Time_Blk                                               0
Cancelled                                                  0
Cancellation_Code                                    4721342
Diverted                                                   0
CRS_Elapsed_Time                                           5
Actual_Elapsed_Time                                   309467
Air_Time                                              309467
Flights                                                    0
Distance                                                   0
Distance_Group                                             0
Carrier_Delay                                        4553443
Weather_Delay                                        4553443
NAS_Delay                                            4553443
Security_Delay                                       4553443
Late_Aircraft_Delay                                  4553443
Duplicate                                                  0
dtype: int64

In [21]:
# The IATA_Code_Originally_Scheduled_Code_Share column is nearly completely null
# Given that the Bureau of Transportation Statistics (BTS.gov) stated that this column shouldn't be 
# used for analysis, and it is completely null for 2019, I will be dropping it and keeping the Unique_Code
# column as suggested by BTS.gov
# Here is the language from BTS.gov:
# ""Code assigned by IATA and commonly used to identify a carrier.""
#""As the same code may have been assigned to different carriers over time, the code is not always unique.""
#""For analysis, use the Unique Carrier Code.""

# Drop the 'IATA_Code_Originally_Scheduled_Code_Share_Airline' column
df = df.drop(columns=['IATA_Code_Originally_Scheduled_Code_Share_Airline'])

In [22]:
df.shape

(5022397, 64)

There are a significant amount of null values for Dep_Delay, Taxi_Out, Taxi_In, Arr_Time.
I believe these are null values because the flights were cancelled.
I will check value counts for the Cancelled column. Value counts for '1' should be close if not the same to the values missing.

In [23]:
df['Cancelled'].value_counts()

Cancelled
0.0    4721342
1.0     301055
Name: count, dtype: int64

301,055 flights were cancelled in 2020.

This is fairly close to the missing values in:

Dep_Time                                              299620
Dep_Delay                                             299683
Dep_Delay_Minutes                                     299683
Dep_Del_15                                            299683
Departure_Delay_Groups                                29
Taxi_Out                                              300426
Wheels_Off                                            300426
Wheels_On                                             302000
Taxi_In                                               302
Arr_Time                                              301999
Arr_Delay                                             309467
Arr_Delay_Minutes                                     309467
Arr_Del_15                                            309467
Arrival_Delay_Groups                                  30

The missing values in:

Cancellation_Code                                    4721342 -- are accounted for because it is the same as the total Flights (5022397) minus the cancelled flights (301,055) - which is 4721342. Therefore 4721342 flights have no cancellation code because they were not cancelled.

After careful consideration, I believe it is best to create a cancelled flights flag in order to prevent confusion in future analysis for delays v. cancellation. 94670009683

In [24]:
# Identify rows where flights were cancelled

cancelled_flights = df['Cancelled'] == 1

In [25]:
# Create a column to indicate if the data is missing due to cancellation

df['Missing_Due_To_Cancellation'] = cancelled_flights

Now I will address columns containing mixed datatypes.

In [26]:
df.dtypes

Year                                 int64
Quarter                              int64
Month                                int64
Day_of_Month                         int64
Day_of_Week                          int64
Flight_Date                         object
Marketing_Airline_Network           object
DOT_ID_Marketing_Airline             int64
IATA_Code_Marketing_Airline         object
Flight_Number_Marketing_Airline      int64
Operating_Airline                   object
DOT_ID_Operating_Airline             int64
IATA_Code_Operating_Airline         object
Tail_Number                         object
Flight_Number_Operating_Airline      int64
Origin_Airport_ID                    int64
Origin_Airport_Seq_ID                int64
Origin_City_Market_ID                int64
Origin                              object
Origin_City_Name                    object
Origin_State                        object
Origin_State_Fips                    int64
Origin_State_Name                   object
Dest_Airport_ID                      int64
Dest_Airport_Seq_ID                  int64
Dest_City_Market_ID                  int64
Dest                                object
Dest_City_Name                      object
Dest_State                          object
Dest_State_Fips                      int64
Dest_State_Name                     object
CRS_Dep_Time                         int64
Dep_Time                           float64
Dep_Delay                          float64
Dep_Delay_Minutes                  float64
Dep_Del_15                         float64
Departure_Delay_Groups             float64
Dep_Time_Blk                        object
Taxi_Out                           float64
Wheels_Off                         float64
Wheels_On                          float64
Taxi_In                            float64
CRS_Arr_Time                         int64
Arr_Time                           float64
Arr_Delay                          float64
Arr_Delay_Minutes                  float64
Arr_Del_15                         float64
Arrival_Delay_Groups               float64
Arr_Time_Blk                        object
Cancelled                          float64
Cancellation_Code                   object
Diverted                           float64
CRS_Elapsed_Time                   float64
Actual_Elapsed_Time                float64
Air_Time                           float64
Flights                            float64
Distance                           float64
Distance_Group                       int64
Carrier_Delay                      float64
Weather_Delay                      float64
NAS_Delay                          float64
Security_Delay                     float64
Late_Aircraft_Delay                float64
Duplicate                           object
Missing_Due_To_Cancellation           bool
dtype: object

In [27]:
# I will change many of these datatypes to reduce the amount of memory needed by reducing int64 to int8, 16, or 32 where possible.
# Additionally, I will change the Flight_Date column to a date datatype, instead of an object.
# Lets change Flight_Date first

# Ensure 'Flight_Date' column is in datetime format
df['Flight_Date'] = pd.to_datetime(df['Flight_Date'], errors='coerce')

In [28]:
# Extract only the date part (since we don't have time in the same column)
df['Flight_Date'] = df['Flight_Date'].dt.date

In [29]:
# Verify the result
print(df.head())
print(df.dtypes)

   Year  Quarter  Month  Day_of_Month  Day_of_Week Flight_Date  \
0  2020        1      1            17            5  2020-01-17
1  2020        1      1            18            6  2020-01-18
2  2020        1      1            19            7  2020-01-19
3  2020        1      1            20            1  2020-01-20
4  2020        1      1            21            2  2020-01-21

  Marketing_Airline_Network  DOT_ID_Marketing_Airline  \
0                        B6                     20409
1                        B6                     20409
2                        B6                     20409
3                        B6                     20409
4                        B6                     20409

  IATA_Code_Marketing_Airline  Flight_Number_Marketing_Airline  \
0                          B6                              942
1                          B6                              942
2                          B6                              942
3                          B6                              942
4                          B6                              942

  Operating_Airline   DOT_ID_Operating_Airline IATA_Code_Operating_Airline  \
0                 B6                     20409                          B6
1                 B6                     20409                          B6
2                 B6                     20409                          B6
3                 B6                     20409                          B6
4                 B6                     20409                          B6

  Tail_Number  Flight_Number_Operating_Airline  Origin_Airport_ID  \
0      N661JB                              942              14027
1      N584JB                              942              14027
2      N662JB                              942              14027
3      N784JB                              942              14027
4      N784JB                              942              14027

   Origin_Airport_Seq_ID  Origin_City_Market_ID Origin  \
0                1402702                  34027    PBI
1                1402702                  34027    PBI
2                1402702                  34027    PBI
3                1402702                  34027    PBI
4                1402702                  34027    PBI

                 Origin_City_Name Origin_State  Origin_State_Fips  \
0  West Palm Beach/Palm Beach, FL           FL                 12
1  West Palm Beach/Palm Beach, FL           FL                 12
2  West Palm Beach/Palm Beach, FL           FL                 12
3  West Palm Beach/Palm Beach, FL           FL                 12
4  West Palm Beach/Palm Beach, FL           FL                 12

  Origin_State_Name  Dest_Airport_ID  Dest_Airport_Seq_ID  \
0           Florida            10529              1052906
1           Florida            10529              1052906
2           Florida            10529              1052906
3           Florida            10529              1052906
4           Florida            10529              1052906

   Dest_City_Market_ID Dest Dest_City_Name Dest_State  Dest_State_Fips  \
0                30529  BDL   Hartford, CT         CT                9
1                30529  BDL   Hartford, CT         CT                9
2                30529  BDL   Hartford, CT         CT                9
3                30529  BDL   Hartford, CT         CT                9
4                30529  BDL   Hartford, CT         CT                9

  Dest_State_Name  CRS_Dep_Time  Dep_Time  Dep_Delay  Dep_Delay_Minutes  \
0     Connecticut          1940    1926.0      -14.0                0.0
1     Connecticut          1940    1926.0      -14.0                0.0
2     Connecticut          1940    1947.0        7.0                7.0
3     Connecticut          1940    1933.0       -7.0                0.0
4     Connecticut          1940    1952.0       12.0               12.0

   Dep_Del_15  Departure_Delay_Groups Dep_Time_Blk  Taxi_Out  Wheels_Off  \
0         0.0                    -1.0    1900-1959      15.0      1941.0
1         0.0                    -1.0    1900-1959      14.0      1940.0
2         0.0                     0.0    1900-1959      11.0      1958.0
3         0.0                    -1.0    1900-1959      27.0      2000.0
4         0.0                     0.0    1900-1959      10.0      2002.0

   Wheels_On  Taxi_In  CRS_Arr_Time  Arr_Time  Arr_Delay  Arr_Delay_Minutes  \
0     2212.0      6.0          2229    2218.0      -11.0                0.0
1     2207.0     13.0          2229    2220.0       -9.0                0.0
2     2217.0      6.0          2229    2223.0       -6.0                0.0
3     2220.0     13.0          2229    2233.0        4.0                4.0
4     2229.0      6.0          2229    2235.0        6.0                6.0

   Arr_Del_15  Arrival_Delay_Groups Arr_Time_Blk  Cancelled Cancellation_Code  \
0         0.0                  -1.0    2200-2259        0.0               NaN
1         0.0                  -1.0    2200-2259        0.0               NaN
2         0.0                  -1.0    2200-2259        0.0               NaN
3         0.0                   0.0    2200-2259        0.0               NaN
4         0.0                   0.0    2200-2259        0.0               NaN

   Diverted  CRS_Elapsed_Time  Actual_Elapsed_Time  Air_Time  Flights  \
0       0.0             169.0                172.0     151.0      1.0
1       0.0             169.0                174.0     147.0      1.0
2       0.0             169.0                156.0     139.0      1.0
3       0.0             169.0                180.0     140.0      1.0
4       0.0             169.0                163.0     147.0      1.0

   Distance  Distance_Group  Carrier_Delay  Weather_Delay  NAS_Delay  \
0    1133.0               5            NaN            NaN        NaN
1    1133.0               5            NaN            NaN        NaN
2    1133.0               5            NaN            NaN        NaN
3    1133.0               5            NaN            NaN        NaN
4    1133.0               5            NaN            NaN        NaN

   Security_Delay  Late_Aircraft_Delay Duplicate  Missing_Due_To_Cancellation
0             NaN                  NaN         N                        False
1             NaN                  NaN         N                        False
2             NaN                  NaN         N                        False
3             NaN                  NaN         N                        False
4             NaN                  NaN         N                        False
Year                                 int64
Quarter                              int64
Month                                int64
Day_of_Month                         int64
Day_of_Week                          int64
Flight_Date                         object
Marketing_Airline_Network           object
DOT_ID_Marketing_Airline             int64
IATA_Code_Marketing_Airline         object
Flight_Number_Marketing_Airline      int64
Operating_Airline                   object
DOT_ID_Operating_Airline             int64
IATA_Code_Operating_Airline         object
Tail_Number                         object
Flight_Number_Operating_Airline      int64
Origin_Airport_ID                    int64
Origin_Airport_Seq_ID                int64
Origin_City_Market_ID                int64
Origin                              object
Origin_City_Name                    object
Origin_State                        object
Origin_State_Fips                    int64
Origin_State_Name                   object
Dest_Airport_ID                      int64
Dest_Airport_Seq_ID                  int64
Dest_City_Market_ID                  int64
Dest                                object
Dest_City_Name                      object
Dest_State                          object
Dest_State_Fips                      int64
Dest_State_Name                     object
CRS_Dep_Time                         int64
Dep_Time                           float64
Dep_Delay                          float64
Dep_Delay_Minutes                  float64
Dep_Del_15                         float64
Departure_Delay_Groups             float64
Dep_Time_Blk                        object
Taxi_Out                           float64
Wheels_Off                         float64
Wheels_On                          float64
Taxi_In                            float64
CRS_Arr_Time                         int64
Arr_Time                           float64
Arr_Delay                          float64
Arr_Delay_Minutes                  float64
Arr_Del_15                         float64
Arrival_Delay_Groups               float64
Arr_Time_Blk                        object
Cancelled                          float64
Cancellation_Code                   object
Diverted                           float64
CRS_Elapsed_Time                   float64
Actual_Elapsed_Time                float64
Air_Time                           float64
Flights                            float64
Distance                           float64
Distance_Group                       int64
Carrier_Delay                      float64
Weather_Delay                      float64
NAS_Delay                          float64
Security_Delay                     float64
Late_Aircraft_Delay                float64
Duplicate                           object
Missing_Due_To_Cancellation           bool
dtype: object

In [30]:
# Change datatypes to maximize available memory

df = df.astype({
    'Year': 'int16',
    'Quarter': 'int16',
    'Month': 'int16',
    'Day_of_Month': 'int16',
    'Day_of_Week': 'int16',
    'DOT_ID_Marketing_Airline': 'int16',
    'Flight_Number_Marketing_Airline': 'int16',
    'DOT_ID_Operating_Airline': 'int16',
    'Flight_Number_Operating_Airline': 'int16',
    'Origin_Airport_ID': 'int16',
    'Origin_Airport_Seq_ID': 'int16',
    'Origin_City_Market_ID': 'int16',
    'Origin_State_Fips': 'int8',
    'Dest_Airport_ID': 'int16',
    'Dest_Airport_Seq_ID': 'int16',
    'Dest_City_Market_ID': 'int16',
    'Dest_State_Fips': 'int16',
    'CRS_Dep_Time': 'int16'
})

In [31]:
df.dtypes

Year                                 int16
Quarter                              int16
Month                                int16
Day_of_Month                         int16
Day_of_Week                          int16
Flight_Date                         object
Marketing_Airline_Network           object
DOT_ID_Marketing_Airline             int16
IATA_Code_Marketing_Airline         object
Flight_Number_Marketing_Airline      int16
Operating_Airline                   object
DOT_ID_Operating_Airline             int16
IATA_Code_Operating_Airline         object
Tail_Number                         object
Flight_Number_Operating_Airline      int16
Origin_Airport_ID                    int16
Origin_Airport_Seq_ID                int16
Origin_City_Market_ID                int16
Origin                              object
Origin_City_Name                    object
Origin_State                        object
Origin_State_Fips                     int8
Origin_State_Name                   object
Dest_Airport_ID                      int16
Dest_Airport_Seq_ID                  int16
Dest_City_Market_ID                  int16
Dest                                object
Dest_City_Name                      object
Dest_State                          object
Dest_State_Fips                      int16
Dest_State_Name                     object
CRS_Dep_Time                         int16
Dep_Time                           float64
Dep_Delay                          float64
Dep_Delay_Minutes                  float64
Dep_Del_15                         float64
Departure_Delay_Groups             float64
Dep_Time_Blk                        object
Taxi_Out                           float64
Wheels_Off                         float64
Wheels_On                          float64
Taxi_In                            float64
CRS_Arr_Time                         int64
Arr_Time                           float64
Arr_Delay                          float64
Arr_Delay_Minutes                  float64
Arr_Del_15                         float64
Arrival_Delay_Groups               float64
Arr_Time_Blk                        object
Cancelled                          float64
Cancellation_Code                   object
Diverted                           float64
CRS_Elapsed_Time                   float64
Actual_Elapsed_Time                float64
Air_Time                           float64
Flights                            float64
Distance                           float64
Distance_Group                       int64
Carrier_Delay                      float64
Weather_Delay                      float64
NAS_Delay                          float64
Security_Delay                     float64
Late_Aircraft_Delay                float64
Duplicate                           object
Missing_Due_To_Cancellation           bool
dtype: object

In [32]:
df.shape

(5022397, 65)

In [33]:
df.head()

,Year,Quarter,Month,Day_of_Month,Day_of_Week,Flight_Date,Marketing_Airline_Network,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,Origin_Airport_ID,Origin_Airport_Seq_ID,Origin_City_Market_ID,Origin,Origin_City_Name,Origin_State,Origin_State_Fips,Origin_State_Name,Dest_Airport_ID,Dest_Airport_Seq_ID,Dest_City_Market_ID,Dest,Dest_City_Name,Dest_State,Dest_State_Fips,Dest_State_Name,CRS_Dep_Time,Dep_Time,Dep_Delay,Dep_Delay_Minutes,Dep_Del_15,Departure_Delay_Groups,Dep_Time_Blk,Taxi_Out,Wheels_Off,Wheels_On,Taxi_In,CRS_Arr_Time,Arr_Time,Arr_Delay,Arr_Delay_Minutes,Arr_Del_15,Arrival_Delay_Groups,Arr_Time_Blk,Cancelled,Cancellation_Code,Diverted,CRS_Elapsed_Time,Actual_Elapsed_Time,Air_Time,Flights,Distance,Distance_Group,Carrier_Delay,Weather_Delay,NAS_Delay,Security_Delay,Late_Aircraft_Delay,Duplicate,Missing_Due_To_Cancellation
0,2020,1,1,17,5,2020-01-17,B6,20409,B6,942,B6,20409,B6,N661JB,942,14027,26446,-31509,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,4330,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,15.0,1941.0,2212.0,6.0,2229,2218.0,-11.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,172.0,151.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,N,False
1,2020,1,1,18,6,2020-01-18,B6,20409,B6,942,B6,20409,B6,N584JB,942,14027,26446,-31509,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,4330,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1926.0,-14.0,0.0,0.0,-1.0,1900-1959,14.0,1940.0,2207.0,13.0,2229,2220.0,-9.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,174.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,N,False
2,2020,1,1,19,7,2020-01-19,B6,20409,B6,942,B6,20409,B6,N662JB,942,14027,26446,-31509,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,4330,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1947.0,7.0,7.0,0.0,0.0,1900-1959,11.0,1958.0,2217.0,6.0,2229,2223.0,-6.0,0.0,0.0,-1.0,2200-2259,0.0,NaN,0.0,169.0,156.0,139.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,N,False
3,2020,1,1,20,1,2020-01-20,B6,20409,B6,942,B6,20409,B6,N784JB,942,14027,26446,-31509,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,4330,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1933.0,-7.0,0.0,0.0,-1.0,1900-1959,27.0,2000.0,2220.0,13.0,2229,2233.0,4.0,4.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,180.0,140.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,N,False
4,2020,1,1,21,2,2020-01-21,B6,20409,B6,942,B6,20409,B6,N784JB,942,14027,26446,-31509,PBI,"West Palm Beach/Palm Beach, FL",FL,12,Florida,10529,4330,30529,BDL,"Hartford, CT",CT,9,Connecticut,1940,1952.0,12.0,12.0,0.0,0.0,1900-1959,10.0,2002.0,2229.0,6.0,2229,2235.0,6.0,6.0,0.0,0.0,2200-2259,0.0,NaN,0.0,169.0,163.0,147.0,1.0,1133.0,5,NaN,NaN,NaN,NaN,NaN,N,False

In [34]:
# Save Clean 2020 Data

df.to_csv(os.path.join(path, 'clean_flights2020.csv'))