In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Set path

path = r'C:\Users\Josh Wattay\OneDrive\Documents\Desktop\Flight Delay Analysis - Raw Data\2020'

In [3]:
# Import Datasets

jan2020 = pd.read_csv(os.path.join(path, '1-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\3523904377.py:3: DtypeWarning: Columns (11,13,57,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jan2020 = pd.read_csv(os.path.join(path, '1-2020.csv'), index_col = False)

In [4]:
feb2020 = pd.read_csv(os.path.join(path, '2-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\4058752750.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  feb2020 = pd.read_csv(os.path.join(path, '2-2020.csv'), index_col = False)

In [5]:
mar2020 = pd.read_csv(os.path.join(path, '3-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\1290954184.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  mar2020 = pd.read_csv(os.path.join(path, '3-2020.csv'), index_col = False)

In [6]:
apr2020 = pd.read_csv(os.path.join(path, '4-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\2526720842.py:1: DtypeWarning: Columns (11,13,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  apr2020 = pd.read_csv(os.path.join(path, '4-2020.csv'), index_col = False)

In [7]:
may2020 = pd.read_csv(os.path.join(path, '5-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\1026981116.py:1: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  may2020 = pd.read_csv(os.path.join(path, '5-2020.csv'), index_col = False)

In [8]:
jun2020 = pd.read_csv(os.path.join(path, '6-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\915477729.py:1: DtypeWarning: Columns (11,13,57) have mixed types. Specify dtype option on import or set low_memory=False.
  jun2020 = pd.read_csv(os.path.join(path, '6-2020.csv'), index_col = False)

In [9]:
jul2020 = pd.read_csv(os.path.join(path, '7-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\2513858088.py:1: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jul2020 = pd.read_csv(os.path.join(path, '7-2020.csv'), index_col = False)

In [10]:
aug2020 = pd.read_csv(os.path.join(path, '8-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\116939697.py:1: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  aug2020 = pd.read_csv(os.path.join(path, '8-2020.csv'), index_col = False)

In [11]:
sep2020 = pd.read_csv(os.path.join(path, '9-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\3074165942.py:1: DtypeWarning: Columns (11,13,57,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  sep2020 = pd.read_csv(os.path.join(path, '9-2020.csv'), index_col = False)

In [12]:
oct2020 = pd.read_csv(os.path.join(path, '10-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\4257207488.py:1: DtypeWarning: Columns (11,13,57,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  oct2020 = pd.read_csv(os.path.join(path, '10-2020.csv'), index_col = False)

In [13]:
nov2020 = pd.read_csv(os.path.join(path, '11-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\3041838301.py:1: DtypeWarning: Columns (11,13,57,78,85,86) have mixed types. Specify dtype option on import or set low_memory=False.
  nov2020 = pd.read_csv(os.path.join(path, '11-2020.csv'), index_col = False)

In [14]:
dec2020 = pd.read_csv(os.path.join(path, '12-2020.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_3560\2096987464.py:1: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  dec2020 = pd.read_csv(os.path.join(path, '12-2020.csv'), index_col = False)

In [15]:
frames = [jan2020, feb2020, mar2020, apr2020, may2020, jun2020, jul2020, aug2020, sep2020, oct2020, nov2020, dec2020]

In [16]:
frames

[        Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2020        1      1          17          5  2020-01-17
 1       2020        1      1          18          6  2020-01-18
 2       2020        1      1          19          7  2020-01-19
 3       2020        1      1          20          1  2020-01-20
 4       2020        1      1          21          2  2020-01-21
 ...      ...      ...    ...         ...        ...         ...
 660551  2020        1      1           6          1  2020-01-06
 660552  2020        1      1           6          1  2020-01-06
 660553  2020        1      1           6          1  2020-01-06
 660554  2020        1      1           6          1  2020-01-06
 660555  2020        1      1           6          1  2020-01-06

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             B6                                      B6
 1                             B6                                      B6
 2                             B6                                      B6
 3                             B6                                      B6
 4                             B6                                      B6
 ...                          ...                                     ...
 660551                        UA                            UA_CODESHARE
 660552                        UA                            UA_CODESHARE
 660553                        UA                            UA_CODESHARE
 660554                        UA                            UA_CODESHARE
 660555                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          20409                          B6  ...
 1                          20409                          B6  ...
 2                          20409                          B6  ...
 3                          20409                          B6  ...
 4                          20409                          B6  ...
 ...                          ...                         ...  ...
 660551                     19977                          UA  ...
 660552                     19977                          UA  ...
 660553                     19977                          UA  ...
 660554                     19977                          UA  ...
 660555                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 660551          NaN           NaN               NaN          NaN
 660552          NaN           NaN               NaN          NaN
 660553          NaN           NaN               NaN          NaN
 660554          NaN           NaN               NaN          NaN
 660555          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 660551             NaN              NaN            NaN         NaN         N
 660552             NaN              NaN            NaN         NaN         N
 660553             NaN              NaN            NaN         NaN         N
 660554             NaN              NaN            NaN         NaN         N
 660555             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 660551           NaN
 660552           NaN
 660553           NaN
 660554           NaN
 660555           NaN

 [660556 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2020        1      2           1          6  2020-02-01
 1       2020        1      2           8          6  2020-02-08
 2       2020        1      2          13          4  2020-02-13
 3       2020        1      2          14          5  2020-02-14
 4       2020        1      2          15          6  2020-02-15
 ...      ...      ...    ...         ...        ...         ...
 623098  2020        1      2           6          4  2020-02-06
 623099  2020        1      2           6          4  2020-02-06
 623100  2020        1      2           6          4  2020-02-06
 623101  2020        1      2           6          4  2020-02-06
 623102  2020        1      2           1          6  2020-02-01

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             AA                            AA_CODESHARE
 1                             AA                            AA_CODESHARE
 2                             AA                            AA_CODESHARE
 3                             AA                            AA_CODESHARE
 4                             AA                            AA_CODESHARE
 ...                          ...                                     ...
 623098                        UA                            UA_CODESHARE
 623099                        UA                            UA_CODESHARE
 623100                        UA                            UA_CODESHARE
 623101                        UA                            UA_CODESHARE
 623102                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19805                          AA  ...
 1                          19805                          AA  ...
 2                          19805                          AA  ...
 3                          19805                          AA  ...
 4                          19805                          AA  ...
 ...                          ...                         ...  ...
 623098                     19977                          UA  ...
 623099                     19977                          UA  ...
 623100                     19977                          UA  ...
 623101                     19977                          UA  ...
 623102                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 623098          NaN           NaN               NaN          NaN
 623099          NaN           NaN               NaN          NaN
 623100          NaN           NaN               NaN          NaN
 623101          NaN           NaN               NaN          NaN
 623102          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 623098             NaN              NaN            NaN         NaN         N
 623099             NaN              NaN            NaN         NaN         N
 623100             NaN              NaN            NaN         NaN         N
 623101             NaN              NaN            NaN         NaN         N
 623102             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 623098           NaN
 623099           NaN
 623100           NaN
 623101           NaN
 623102           NaN

 [623103 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2020        1      3           9          1  2020-03-09
 1       2020        1      3           9          1  2020-03-09
 2       2020        1      3           7          6  2020-03-07
 3       2020        1      3           7          6  2020-03-07
 4       2020        1      3           7          6  2020-03-07
 ...      ...      ...    ...         ...        ...         ...
 701269  2020        1      3           6          5  2020-03-06
 701270  2020        1      3           7          6  2020-03-07
 701271  2020        1      3           8          7  2020-03-08
 701272  2020        1      3           9          1  2020-03-09
 701273  2020        1      3          10          2  2020-03-10

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             DL                            DL_CODESHARE
 1                             DL                            DL_CODESHARE
 2                             DL                            DL_CODESHARE
 3                             DL                            DL_CODESHARE
 4                             DL                            DL_CODESHARE
 ...                          ...                                     ...
 701269                        NK                                      NK
 701270                        NK                                      NK
 701271                        NK                                      NK
 701272                        NK                                      NK
 701273                        NK                                      NK

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19790                          DL  ...
 1                          19790                          DL  ...
 2                          19790                          DL  ...
 3                          19790                          DL  ...
 4                          19790                          DL  ...
 ...                          ...                         ...  ...
 701269                     20416                          NK  ...
 701270                     20416                          NK  ...
 701271                     20416                          NK  ...
 701272                     20416                          NK  ...
 701273                     20416                          NK  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 701269          NaN           NaN               NaN          NaN
 701270          NaN           NaN               NaN          NaN
 701271          NaN           NaN               NaN          NaN
 701272          NaN           NaN               NaN          NaN
 701273          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 701269             NaN              NaN            NaN         NaN         N
 701270             NaN              NaN            NaN         NaN         N
 701271             NaN              NaN            NaN         NaN         N
 701272             NaN              NaN            NaN         NaN         N
 701273             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 701269           NaN
 701270           NaN
 701271           NaN
 701272           NaN
 701273           NaN

 [701274 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2020        2      4           4          6  2020-04-04
 1       2020        2      4          10          5  2020-04-10
 2       2020        2      4          13          1  2020-04-13
 3       2020        2      4          12          7  2020-04-12
 4       2020        2      4          16          4  2020-04-16
 ...      ...      ...    ...         ...        ...         ...
 331233  2020        2      4           1          3  2020-04-01
 331234  2020        2      4           1          3  2020-04-01
 331235  2020        2      4           1          3  2020-04-01
 331236  2020        2      4           1          3  2020-04-01
 331237  2020        2      4           1          3  2020-04-01

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             G4                                      G4
 1                             G4                                      G4
 2                             G4                                      G4
 3                             G4                                      G4
 4                             G4                                      G4
 ...                          ...                                     ...
 331233                        UA                            UA_CODESHARE
 331234                        UA                            UA_CODESHARE
 331235                        UA                            UA_CODESHARE
 331236                        UA                            UA_CODESHARE
 331237                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          20368                          G4  ...
 1                          20368                          G4  ...
 2                          20368                          G4  ...
 3                          20368                          G4  ...
 4                          20368                          G4  ...
 ...                          ...                         ...  ...
 331233                     19977                          UA  ...
 331234                     19977                          UA  ...
 331235                     19977                          UA  ...
 331236                     19977                          UA  ...
 331237                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 331233          NaN           NaN               NaN          NaN
 331234          NaN           NaN               NaN          NaN
 331235          NaN           NaN               NaN          NaN
 331236          NaN           NaN               NaN          NaN
 331237          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 331233             NaN              NaN            NaN         NaN         N
 331234             NaN              NaN            NaN         NaN         N
 331235             NaN              NaN            NaN         NaN         N
 331236             NaN              NaN            NaN         NaN         N
 331237             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 331233           NaN
 331234           NaN
 331235           NaN
 331236           NaN
 331237           NaN

 [331238 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2020        2      5          31          7  2020-05-31
 1       2020        2      5          31          7  2020-05-31
 2       2020        2      5          31          7  2020-05-31
 3       2020        2      5          31          7  2020-05-31
 4       2020        2      5          31          7  2020-05-31
 ...      ...      ...    ...         ...        ...         ...
 192407  2020        2      5          24          7  2020-05-24
 192408  2020        2      5          24          7  2020-05-24
 192409  2020        2      5          24          7  2020-05-24
 192410  2020        2      5          24          7  2020-05-24
 192411  2020        2      5          24          7  2020-05-24

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             WN                                      WN
 1                             WN                                      WN
 2                             WN                                      WN
 3                             WN                                      WN
 4                             WN                                      WN
 ...                          ...                                     ...
 192407                        UA                            UA_CODESHARE
 192408                        UA                            UA_CODESHARE
 192409                        UA                            UA_CODESHARE
 192410                        UA                            UA_CODESHARE
 192411                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19393                          WN  ...
 1                          19393                          WN  ...

In [17]:
type(frames)

list

In [18]:
#Concatinate the Dataframes using Default Options

flights2020 = pd.concat(frames)

In [19]:
flights2020.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
0,2020,1,1,17,5,2020-01-17,B6,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,2020,1,1,18,6,2020-01-18,B6,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,2020,1,1,19,7,2020-01-19,B6,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,2020,1,1,20,1,2020-01-20,B6,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,2020,1,1,21,2,2020-01-21,B6,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [20]:
flights2020.shape

(5022397, 120)

In [21]:
flights2020 = flights2020.drop(columns=[
    'Operated_or_Branded_Code_Share_Partners', 
    'Originally_Scheduled_Code_Share_Airline', 
    'DOT_ID_Originally_Scheduled_Code_Share_Airline',
    'Flight_Num_Originally_Scheduled_Code_Share_Airline',
    'OriginWac', 'DestWac', 'DivAirportLandings', 'DivReachedDest',
    'DivActualElapsedTime', 'DivArrDelay', 
    'Div1Airport', 'Div1AirportID',
    'Div1AirportSeqID', 'Div1WheelsOn', 'Div1TotalGTime', 
    'Div1LongestGTime', 'Div1WheelsOff', 'Div1TailNum',
    'Div2Airport', 'Div2AirportID',
    'Div2AirportSeqID', 'Div2WheelsOn', 'Div2TotalGTime', 
    'Div2LongestGTime', 'Div2WheelsOff', 'Div2TailNum',
    'Div3Airport', 'Div3AirportID',
    'Div3AirportSeqID', 'Div3WheelsOn', 'Div3TotalGTime', 
    'Div3LongestGTime', 'Div3WheelsOff', 'Div3TailNum',
    'Div4Airport', 'Div4AirportID',
    'Div4AirportSeqID', 'Div4WheelsOn', 'Div4TotalGTime', 
    'Div4LongestGTime', 'Div4WheelsOff', 'Div4TailNum',
    'Div5Airport', 'Div5AirportID',
    'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime', 
    'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum', 'Unnamed: 119'])

In [22]:
flights2020.shape

(5022397, 69)

In [23]:
flights2020.to_csv(os.path.join(path, 'flights2020.csv'))