In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Set path

path = r'C:\Users\Josh Wattay\OneDrive\Documents\Desktop\Flight Delay Analysis - Raw Data\2023'

In [3]:
# Import Datasets

jan2023 = pd.read_csv(os.path.join(path, '1-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\2836491308.py:3: DtypeWarning: Columns (11,13,57,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jan2023 = pd.read_csv(os.path.join(path, '1-2023.csv'), index_col = False)

In [4]:
# Import Datasets

feb2023 = pd.read_csv(os.path.join(path, '2-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\1182875543.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  feb2023 = pd.read_csv(os.path.join(path, '2-2023.csv'), index_col = False)

In [5]:
# Import Datasets

mar2023 = pd.read_csv(os.path.join(path, '3-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\820702875.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  mar2023 = pd.read_csv(os.path.join(path, '3-2023.csv'), index_col = False)

In [6]:
# Import Datasets

apr2023 = pd.read_csv(os.path.join(path, '4-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\448314195.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  apr2023 = pd.read_csv(os.path.join(path, '4-2023.csv'), index_col = False)

In [7]:
# Import Datasets

may2023 = pd.read_csv(os.path.join(path, '5-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\879850055.py:3: DtypeWarning: Columns (11,13,86,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  may2023 = pd.read_csv(os.path.join(path, '5-2023.csv'), index_col = False)

In [8]:
# Import Datasets

jun2023 = pd.read_csv(os.path.join(path, '6-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\2038318949.py:3: DtypeWarning: Columns (11,13,86,93,94,101) have mixed types. Specify dtype option on import or set low_memory=False.
  jun2023 = pd.read_csv(os.path.join(path, '6-2023.csv'), index_col = False)

In [9]:
# Import Datasets

jul2023 = pd.read_csv(os.path.join(path, '7-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\851283316.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jul2023 = pd.read_csv(os.path.join(path, '7-2023.csv'), index_col = False)

In [10]:
# Import Datasets

aug2023 = pd.read_csv(os.path.join(path, '8-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\3021994675.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  aug2023 = pd.read_csv(os.path.join(path, '8-2023.csv'), index_col = False)

In [11]:
# Import Datasets

sep2023 = pd.read_csv(os.path.join(path, '9-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\2574026574.py:3: DtypeWarning: Columns (11,13,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  sep2023 = pd.read_csv(os.path.join(path, '9-2023.csv'), index_col = False)

In [12]:
# Import Datasets

oct2023 = pd.read_csv(os.path.join(path, '10-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\3625001011.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  oct2023 = pd.read_csv(os.path.join(path, '10-2023.csv'), index_col = False)

In [13]:
# Import Datasets

nov2023 = pd.read_csv(os.path.join(path, '11-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\4005808976.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  nov2023 = pd.read_csv(os.path.join(path, '11-2023.csv'), index_col = False)

In [14]:
# Import Datasets

dec2023 = pd.read_csv(os.path.join(path, '12-2023.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_2544\2873163579.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  dec2023 = pd.read_csv(os.path.join(path, '12-2023.csv'), index_col = False)

In [15]:
frames = [jan2023, feb2023, mar2023, apr2023, may2023, jun2023, jul2023, aug2023, sep2023, oct2023, nov2023, dec2023]

In [16]:
frames

[        Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2023        1      1          22          7  2023-01-22
 1       2023        1      1          22          7  2023-01-22
 2       2023        1      1          22          7  2023-01-22
 3       2023        1      1          22          7  2023-01-22
 4       2023        1      1          22          7  2023-01-22
 ...      ...      ...    ...         ...        ...         ...
 573872  2023        1      1           1          7  2023-01-01
 573873  2023        1      1           1          7  2023-01-01
 573874  2023        1      1           1          7  2023-01-01
 573875  2023        1      1           1          7  2023-01-01
 573876  2023        1      1           1          7  2023-01-01

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             B6                                      B6
 1                             B6                                      B6
 2                             B6                                      B6
 3                             B6                                      B6
 4                             B6                                      B6
 ...                          ...                                     ...
 573872                        UA                            UA_CODESHARE
 573873                        UA                            UA_CODESHARE
 573874                        UA                            UA_CODESHARE
 573875                        UA                            UA_CODESHARE
 573876                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          20409                          B6  ...
 1                          20409                          B6  ...
 2                          20409                          B6  ...
 3                          20409                          B6  ...
 4                          20409                          B6  ...
 ...                          ...                         ...  ...
 573872                     19977                          UA  ...
 573873                     19977                          UA  ...
 573874                     19977                          UA  ...
 573875                     19977                          UA  ...
 573876                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 573872          NaN           NaN               NaN          NaN
 573873          NaN           NaN               NaN          NaN
 573874          NaN           NaN               NaN          NaN
 573875          NaN           NaN               NaN          NaN
 573876          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 573872             NaN              NaN            NaN         NaN         N
 573873             NaN              NaN            NaN         NaN         N
 573874             NaN              NaN            NaN         NaN         N
 573875             NaN              NaN            NaN         NaN         N
 573876             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 573872           NaN
 573873           NaN
 573874           NaN
 573875           NaN
 573876           NaN

 [573877 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2023        1      2           7          2  2023-02-07
 1       2023        1      2           7          2  2023-02-07
 2       2023        1      2           7          2  2023-02-07
 3       2023        1      2           7          2  2023-02-07
 4       2023        1      2           7          2  2023-02-07
 ...      ...      ...    ...         ...        ...         ...
 536224  2023        1      2           7          2  2023-02-07
 536225  2023        1      2           7          2  2023-02-07
 536226  2023        1      2           7          2  2023-02-07
 536227  2023        1      2           7          2  2023-02-07
 536228  2023        1      2           7          2  2023-02-07

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             B6                                      B6
 1                             B6                                      B6
 2                             B6                                      B6
 3                             B6                                      B6
 4                             B6                                      B6
 ...                          ...                                     ...
 536224                        B6                                      B6
 536225                        B6                                      B6
 536226                        B6                                      B6
 536227                        B6                                      B6
 536228                        B6                                      B6

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          20409                          B6  ...
 1                          20409                          B6  ...
 2                          20409                          B6  ...
 3                          20409                          B6  ...
 4                          20409                          B6  ...
 ...                          ...                         ...  ...
 536224                     20409                          B6  ...
 536225                     20409                          B6  ...
 536226                     20409                          B6  ...
 536227                     20409                          B6  ...
 536228                     20409                          B6  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 536224          NaN           NaN               NaN          NaN
 536225          NaN           NaN               NaN          NaN
 536226          NaN           NaN               NaN          NaN
 536227          NaN           NaN               NaN          NaN
 536228          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 536224             NaN              NaN            NaN         NaN         N
 536225             NaN              NaN            NaN         NaN         N
 536226             NaN              NaN            NaN         NaN         N
 536227             NaN              NaN            NaN         NaN         N
 536228             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 536224           NaN
 536225           NaN
 536226           NaN
 536227           NaN
 536228           NaN

 [536229 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2023        1      3           1          3  2023-03-01
 1       2023        1      3           1          3  2023-03-01
 2       2023        1      3           1          3  2023-03-01
 3       2023        1      3           1          3  2023-03-01
 4       2023        1      3           1          3  2023-03-01
 ...      ...      ...    ...         ...        ...         ...
 616229  2023        1      3           6          1  2023-03-06
 616230  2023        1      3           8          3  2023-03-08
 616231  2023        1      3           9          4  2023-03-09
 616232  2023        1      3          10          5  2023-03-10
 616233  2023        1      3          12          7  2023-03-12

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             WN                                      WN
 1                             WN                                      WN
 2                             WN                                      WN
 3                             WN                                      WN
 4                             WN                                      WN
 ...                          ...                                     ...
 616229                        AA                            AA_CODESHARE
 616230                        AA                            AA_CODESHARE
 616231                        AA                            AA_CODESHARE
 616232                        AA                            AA_CODESHARE
 616233                        AA                            AA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19393                          WN  ...
 1                          19393                          WN  ...
 2                          19393                          WN  ...
 3                          19393                          WN  ...
 4                          19393                          WN  ...
 ...                          ...                         ...  ...
 616229                     19805                          AA  ...
 616230                     19805                          AA  ...
 616231                     19805                          AA  ...
 616232                     19805                          AA  ...
 616233                     19805                          AA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 616229          NaN           NaN               NaN          NaN
 616230          NaN           NaN               NaN          NaN
 616231          NaN           NaN               NaN          NaN
 616232          NaN           NaN               NaN          NaN
 616233          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 616229             NaN              NaN            NaN         NaN         N
 616230             NaN              NaN            NaN         NaN         N
 616231             NaN              NaN            NaN         NaN         N
 616232             NaN              NaN            NaN         NaN         N
 616233             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 616229           NaN
 616230           NaN
 616231           NaN
 616232           NaN
 616233           NaN

 [616234 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2023        2      4          19          3  2023-04-19
 1       2023        2      4          19          3  2023-04-19
 2       2023        2      4          19          3  2023-04-19
 3       2023        2      4          19          3  2023-04-19
 4       2023        2      4          19          3  2023-04-19
 ...      ...      ...    ...         ...        ...         ...
 596671  2023        2      4          26          3  2023-04-26
 596672  2023        2      4          26          3  2023-04-26
 596673  2023        2      4          26          3  2023-04-26
 596674  2023        2      4          26          3  2023-04-26
 596675  2023        2      4          26          3  2023-04-26

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             WN                                      WN
 1                             WN                                      WN
 2                             WN                                      WN
 3                             WN                                      WN
 4                             WN                                      WN
 ...                          ...                                     ...
 596671                        UA                                      UA
 596672                        UA                                      UA
 596673                        UA                                      UA
 596674                        UA                                      UA
 596675                        UA                                      UA

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19393                          WN  ...
 1                          19393                          WN  ...
 2                          19393                          WN  ...
 3                          19393                          WN  ...
 4                          19393                          WN  ...
 ...                          ...                         ...  ...
 596671                     19977                          UA  ...
 596672                     19977                          UA  ...
 596673                     19977                          UA  ...
 596674                     19977                          UA  ...
 596675                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 596671          NaN           NaN               NaN          NaN
 596672          NaN           NaN               NaN          NaN
 596673          NaN           NaN               NaN          NaN
 596674          NaN           NaN               NaN          NaN
 596675          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 596671             NaN              NaN            NaN         NaN         N
 596672             NaN              NaN            NaN         NaN         N
 596673             NaN              NaN            NaN         NaN         N
 596674             NaN              NaN            NaN         NaN         N
 596675             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 596671           NaN
 596672           NaN
 596673           NaN
 596674           NaN
 596675           NaN

 [596676 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2023        2      5           8          1  2023-05-08
 1       2023        2      5           8          1  2023-05-08
 2       2023        2      5           8          1  2023-05-08
 3       2023        2      5           8          1  2023-05-08
 4       2023        2      5           8          1  2023-05-08
 ...      ...      ...    ...         ...        ...         ...
 616625  2023        2      5          30          2  2023-05-30
 616626  2023        2      5          30          2  2023-05-30
 616627  2023        2      5          31          3  2023-05-31
 616628  2023        2      5          31          3  2023-05-31
 616629  2023        2      5          31          3  2023-05-31

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             UA                            UA_CODESHARE
 1                             UA                            UA_CODESHARE
 2                             UA                            UA_CODESHARE
 3                             UA                            UA_CODESHARE
 4                             UA                            UA_CODESHARE
 ...                          ...                                     ...
 616625                        B6                                      B6
 616626                        B6                                      B6
 616627                        B6                                      B6
 616628                        B6                                      B6
 616629                        B6                                      B6

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19977                          UA  ...
 1                          19977                          UA  ...

In [17]:
type(frames)

list

In [18]:
#Concatinate the Dataframes using Default Options

flights2023 = pd.concat(frames)

In [19]:
flights2023.shape

(7278739, 120)

In [20]:
flights2023 = flights2023.drop(columns=[
    'Operated_or_Branded_Code_Share_Partners', 
    'Originally_Scheduled_Code_Share_Airline', 
    'DOT_ID_Originally_Scheduled_Code_Share_Airline',
    'Flight_Num_Originally_Scheduled_Code_Share_Airline',
    'OriginWac', 'DestWac', 'DivAirportLandings', 'DivReachedDest',
    'DivActualElapsedTime', 'DivArrDelay', 
    'Div1Airport', 'Div1AirportID',
    'Div1AirportSeqID', 'Div1WheelsOn', 'Div1TotalGTime', 
    'Div1LongestGTime', 'Div1WheelsOff', 'Div1TailNum',
    'Div2Airport', 'Div2AirportID',
    'Div2AirportSeqID', 'Div2WheelsOn', 'Div2TotalGTime', 
    'Div2LongestGTime', 'Div2WheelsOff', 'Div2TailNum',
    'Div3Airport', 'Div3AirportID',
    'Div3AirportSeqID', 'Div3WheelsOn', 'Div3TotalGTime', 
    'Div3LongestGTime', 'Div3WheelsOff', 'Div3TailNum',
    'Div4Airport', 'Div4AirportID',
    'Div4AirportSeqID', 'Div4WheelsOn', 'Div4TotalGTime', 
    'Div4LongestGTime', 'Div4WheelsOff', 'Div4TailNum',
    'Div5Airport', 'Div5AirportID',
    'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime', 
    'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum', 'Unnamed: 119'])

In [21]:
flights2023.shape

(7278739, 69)

In [22]:
flights2023.to_csv(os.path.join(path, 'flights2023.csv'))