In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Set path

path = r'C:\Users\Josh Wattay\OneDrive\Documents\Desktop\Flight Delay Analysis - Raw Data\2022'

In [3]:
# Import Datasets

jan2022 = pd.read_csv(os.path.join(path, '1-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\3280920030.py:3: DtypeWarning: Columns (11,13,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jan2022 = pd.read_csv(os.path.join(path, '1-2022.csv'), index_col = False)

In [4]:
# Import Datasets

feb2022 = pd.read_csv(os.path.join(path, '2-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\1586372324.py:3: DtypeWarning: Columns (11,13,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  feb2022 = pd.read_csv(os.path.join(path, '2-2022.csv'), index_col = False)

In [5]:
# Import Datasets

mar2022 = pd.read_csv(os.path.join(path, '3-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\1963545753.py:3: DtypeWarning: Columns (11,13,86,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  mar2022 = pd.read_csv(os.path.join(path, '3-2022.csv'), index_col = False)

In [6]:
# Import Datasets

apr2022 = pd.read_csv(os.path.join(path, '4-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\587041710.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  apr2022 = pd.read_csv(os.path.join(path, '4-2022.csv'), index_col = False)

In [7]:
# Import Datasets

may2022 = pd.read_csv(os.path.join(path, '5-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\3535474083.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  may2022 = pd.read_csv(os.path.join(path, '5-2022.csv'), index_col = False)

In [8]:
# Import Datasets

jun2022 = pd.read_csv(os.path.join(path, '6-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\1637288610.py:3: DtypeWarning: Columns (11,13,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jun2022 = pd.read_csv(os.path.join(path, '6-2022.csv'), index_col = False)

In [9]:
# Import Datasets

jul2022 = pd.read_csv(os.path.join(path, '7-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\3700451642.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jul2022 = pd.read_csv(os.path.join(path, '7-2022.csv'), index_col = False)

In [10]:
# Import Datasets

aug2022 = pd.read_csv(os.path.join(path, '8-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\758977663.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  aug2022 = pd.read_csv(os.path.join(path, '8-2022.csv'), index_col = False)

In [11]:
# Import Datasets

sep2022 = pd.read_csv(os.path.join(path, '9-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\2217835209.py:3: DtypeWarning: Columns (11,13,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  sep2022 = pd.read_csv(os.path.join(path, '9-2022.csv'), index_col = False)

In [12]:
# Import Datasets

oct2022 = pd.read_csv(os.path.join(path, '10-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\1936777742.py:3: DtypeWarning: Columns (11,13,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  oct2022 = pd.read_csv(os.path.join(path, '10-2022.csv'), index_col = False)

In [13]:
# Import Datasets

nov2022 = pd.read_csv(os.path.join(path, '11-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\3152586911.py:3: DtypeWarning: Columns (11,13,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  nov2022 = pd.read_csv(os.path.join(path, '11-2022.csv'), index_col = False)

In [14]:
# Import Datasets

dec2022 = pd.read_csv(os.path.join(path, '12-2022.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_9888\541703496.py:3: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  dec2022 = pd.read_csv(os.path.join(path, '12-2022.csv'), index_col = False)

In [15]:
frames = [jan2022, feb2022, mar2022, apr2022, may2022, jun2022, jul2022, aug2022, sep2022, oct2022, nov2022, dec2022]

In [16]:
frames

[        Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2022        1      1           6          4  2022-01-06
 1       2022        1      1           6          4  2022-01-06
 2       2022        1      1           6          4  2022-01-06
 3       2022        1      1           6          4  2022-01-06
 4       2022        1      1           6          4  2022-01-06
 ...      ...      ...    ...         ...        ...         ...
 563732  2022        1      1          24          1  2022-01-24
 563733  2022        1      1          24          1  2022-01-24
 563734  2022        1      1          24          1  2022-01-24
 563735  2022        1      1          24          1  2022-01-24
 563736  2022        1      1          24          1  2022-01-24

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             DL                                      DL
 1                             DL                                      DL
 2                             DL                                      DL
 3                             DL                                      DL
 4                             DL                                      DL
 ...                          ...                                     ...
 563732                        UA                            UA_CODESHARE
 563733                        UA                            UA_CODESHARE
 563734                        UA                            UA_CODESHARE
 563735                        UA                            UA_CODESHARE
 563736                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19790                          DL  ...
 1                          19790                          DL  ...
 2                          19790                          DL  ...
 3                          19790                          DL  ...
 4                          19790                          DL  ...
 ...                          ...                         ...  ...
 563732                     19977                          UA  ...
 563733                     19977                          UA  ...
 563734                     19977                          UA  ...
 563735                     19977                          UA  ...
 563736                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 563732          NaN           NaN               NaN          NaN
 563733          NaN           NaN               NaN          NaN
 563734          NaN           NaN               NaN          NaN
 563735          NaN           NaN               NaN          NaN
 563736          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 563732             NaN              NaN            NaN         NaN         N
 563733             NaN              NaN            NaN         NaN         N
 563734             NaN              NaN            NaN         NaN         N
 563735             NaN              NaN            NaN         NaN         N
 563736             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 563732           NaN
 563733           NaN
 563734           NaN
 563735           NaN
 563736           NaN

 [563737 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2022        1      2          28          1  2022-02-28
 1       2022        1      2          28          1  2022-02-28
 2       2022        1      2          28          1  2022-02-28
 3       2022        1      2          28          1  2022-02-28
 4       2022        1      2          28          1  2022-02-28
 ...      ...      ...    ...         ...        ...         ...
 519947  2022        1      2          25          5  2022-02-25
 519948  2022        1      2          23          3  2022-02-23
 519949  2022        1      2          22          2  2022-02-22
 519950  2022        1      2          16          3  2022-02-16
 519951  2022        1      2          15          2  2022-02-15

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             UA                            UA_CODESHARE
 1                             UA                            UA_CODESHARE
 2                             UA                            UA_CODESHARE
 3                             UA                            UA_CODESHARE
 4                             UA                            UA_CODESHARE
 ...                          ...                                     ...
 519947                        UA                            UA_CODESHARE
 519948                        UA                            UA_CODESHARE
 519949                        UA                            UA_CODESHARE
 519950                        UA                            UA_CODESHARE
 519951                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19977                          UA  ...
 1                          19977                          UA  ...
 2                          19977                          UA  ...
 3                          19977                          UA  ...
 4                          19977                          UA  ...
 ...                          ...                         ...  ...
 519947                     19977                          UA  ...
 519948                     19977                          UA  ...
 519949                     19977                          UA  ...
 519950                     19977                          UA  ...
 519951                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 519947          NaN           NaN               NaN          NaN
 519948          NaN           NaN               NaN          NaN
 519949          NaN           NaN               NaN          NaN
 519950          NaN           NaN               NaN          NaN
 519951          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 519947             NaN              NaN            NaN         NaN         N
 519948             NaN              NaN            NaN         NaN         N
 519949             NaN              NaN            NaN         NaN         N
 519950             NaN              NaN            NaN         NaN         N
 519951             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 519947           NaN
 519948           NaN
 519949           NaN
 519950           NaN
 519951           NaN

 [519952 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2022        1      3           8          2  2022-03-08
 1       2022        1      3          12          6  2022-03-12
 2       2022        1      3          15          2  2022-03-15
 3       2022        1      3          19          6  2022-03-19
 4       2022        1      3          22          2  2022-03-22
 ...      ...      ...    ...         ...        ...         ...
 590537  2022        1      3          31          4  2022-03-31
 590538  2022        1      3          17          4  2022-03-17
 590539  2022        1      3           8          2  2022-03-08
 590540  2022        1      3          25          5  2022-03-25
 590541  2022        1      3           7          1  2022-03-07

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             DL                                      DL
 1                             DL                                      DL
 2                             DL                                      DL
 3                             DL                                      DL
 4                             DL                                      DL
 ...                          ...                                     ...
 590537                        UA                            UA_CODESHARE
 590538                        UA                            UA_CODESHARE
 590539                        UA                            UA_CODESHARE
 590540                        UA                            UA_CODESHARE
 590541                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19790                          DL  ...
 1                          19790                          DL  ...
 2                          19790                          DL  ...
 3                          19790                          DL  ...
 4                          19790                          DL  ...
 ...                          ...                         ...  ...
 590537                     19977                          UA  ...
 590538                     19977                          UA  ...
 590539                     19977                          UA  ...
 590540                     19977                          UA  ...
 590541                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 590537          NaN           NaN               NaN          NaN
 590538          NaN           NaN               NaN          NaN
 590539          NaN           NaN               NaN          NaN
 590540          NaN           NaN               NaN          NaN
 590541          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 590537             NaN              NaN            NaN         NaN         N
 590538             NaN              NaN            NaN         NaN         N
 590539             NaN              NaN            NaN         NaN         N
 590540             NaN              NaN            NaN         NaN         N
 590541             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 590537           NaN
 590538           NaN
 590539           NaN
 590540           NaN
 590541           NaN

 [590542 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2022        2      4           4          1  2022-04-04
 1       2022        2      4           4          1  2022-04-04
 2       2022        2      4           4          1  2022-04-04
 3       2022        2      4           4          1  2022-04-04
 4       2022        2      4           4          1  2022-04-04
 ...      ...      ...    ...         ...        ...         ...
 580285  2022        2      4           4          1  2022-04-04
 580286  2022        2      4           4          1  2022-04-04
 580287  2022        2      4           4          1  2022-04-04
 580288  2022        2      4           4          1  2022-04-04
 580289  2022        2      4           4          1  2022-04-04

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             UA                            UA_CODESHARE
 1                             UA                            UA_CODESHARE
 2                             UA                            UA_CODESHARE
 3                             UA                            UA_CODESHARE
 4                             UA                            UA_CODESHARE
 ...                          ...                                     ...
 580285                        UA                            UA_CODESHARE
 580286                        UA                            UA_CODESHARE
 580287                        UA                            UA_CODESHARE
 580288                        UA                            UA_CODESHARE
 580289                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19977                          UA  ...
 1                          19977                          UA  ...
 2                          19977                          UA  ...
 3                          19977                          UA  ...
 4                          19977                          UA  ...
 ...                          ...                         ...  ...
 580285                     19977                          UA  ...
 580286                     19977                          UA  ...
 580287                     19977                          UA  ...
 580288                     19977                          UA  ...
 580289                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 580285          NaN           NaN               NaN          NaN
 580286          NaN           NaN               NaN          NaN
 580287          NaN           NaN               NaN          NaN
 580288          NaN           NaN               NaN          NaN
 580289          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 580285             NaN              NaN            NaN         NaN         N
 580286             NaN              NaN            NaN         NaN         N
 580287             NaN              NaN            NaN         NaN         N
 580288             NaN              NaN            NaN         NaN         N
 580289             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 580285           NaN
 580286           NaN
 580287           NaN
 580288           NaN
 580289           NaN

 [580290 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2022        2      5           3          2  2022-05-03
 1       2022        2      5           4          3  2022-05-04
 2       2022        2      5           1          7  2022-05-01
 3       2022        2      5           2          1  2022-05-02
 4       2022        2      5           3          2  2022-05-03
 ...      ...      ...    ...         ...        ...         ...
 602945  2022        2      5          29          7  2022-05-29
 602946  2022        2      5          29          7  2022-05-29
 602947  2022        2      5          29          7  2022-05-29
 602948  2022        2      5          29          7  2022-05-29
 602949  2022        2      5          29          7  2022-05-29

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             AA                            AA_CODESHARE
 1                             AA                            AA_CODESHARE
 2                             AA                            AA_CODESHARE
 3                             AA                            AA_CODESHARE
 4                             AA                            AA_CODESHARE
 ...                          ...                                     ...
 602945                        DL                            DL_CODESHARE
 602946                        DL                            DL_CODESHARE
 602947                        DL                            DL_CODESHARE
 602948                        DL                            DL_CODESHARE
 602949                        DL                            DL_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19805                          AA  ...
 1                          19805                          AA  ...

In [17]:
type(frames)

list

In [18]:
#Concatinate the Dataframes using Default Options

flights2022 = pd.concat(frames)

In [19]:
flights2022.shape

(7013508, 120)

In [20]:
flights2022 = flights2022.drop(columns=[
    'Operated_or_Branded_Code_Share_Partners', 
    'Originally_Scheduled_Code_Share_Airline', 
    'DOT_ID_Originally_Scheduled_Code_Share_Airline',
    'Flight_Num_Originally_Scheduled_Code_Share_Airline',
    'OriginWac', 'DestWac', 'DivAirportLandings', 'DivReachedDest',
    'DivActualElapsedTime', 'DivArrDelay', 
    'Div1Airport', 'Div1AirportID',
    'Div1AirportSeqID', 'Div1WheelsOn', 'Div1TotalGTime', 
    'Div1LongestGTime', 'Div1WheelsOff', 'Div1TailNum',
    'Div2Airport', 'Div2AirportID',
    'Div2AirportSeqID', 'Div2WheelsOn', 'Div2TotalGTime', 
    'Div2LongestGTime', 'Div2WheelsOff', 'Div2TailNum',
    'Div3Airport', 'Div3AirportID',
    'Div3AirportSeqID', 'Div3WheelsOn', 'Div3TotalGTime', 
    'Div3LongestGTime', 'Div3WheelsOff', 'Div3TailNum',
    'Div4Airport', 'Div4AirportID',
    'Div4AirportSeqID', 'Div4WheelsOn', 'Div4TotalGTime', 
    'Div4LongestGTime', 'Div4WheelsOff', 'Div4TailNum',
    'Div5Airport', 'Div5AirportID',
    'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime', 
    'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum', 'Unnamed: 119'])

In [21]:
flights2022.shape

(7013508, 69)

In [22]:
flights2022.to_csv(os.path.join(path, 'flights2022.csv'))