In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Set path

path = r'C:\Users\Josh Wattay\OneDrive\Documents\Desktop\Flight Delay Analysis - Raw Data\2019'

In [3]:
# Import Datasets

jan2019 = pd.read_csv(os.path.join(path, '1-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\3029557399.py:3: DtypeWarning: Columns (11,13,57,86,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  jan2019 = pd.read_csv(os.path.join(path, '1-2019.csv'), index_col = False)

In [4]:
feb2019 = pd.read_csv(os.path.join(path, '2-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\1060989675.py:1: DtypeWarning: Columns (11,13,57,86,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  feb2019 = pd.read_csv(os.path.join(path, '2-2019.csv'), index_col = False)

In [5]:
mar2019 = pd.read_csv(os.path.join(path, '3-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\3165059037.py:1: DtypeWarning: Columns (11,13,57,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  mar2019 = pd.read_csv(os.path.join(path, '3-2019.csv'), index_col = False)

In [6]:
apr2019 = pd.read_csv(os.path.join(path, '4-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\1775534395.py:1: DtypeWarning: Columns (11,13,57,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  apr2019 = pd.read_csv(os.path.join(path, '4-2019.csv'), index_col = False)

In [7]:
may2019 = pd.read_csv(os.path.join(path, '5-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\921985669.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  may2019 = pd.read_csv(os.path.join(path, '5-2019.csv'), index_col = False)

In [8]:
jun2019 = pd.read_csv(os.path.join(path, '6-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\3396006896.py:1: DtypeWarning: Columns (11,13,57,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jun2019 = pd.read_csv(os.path.join(path, '6-2019.csv'), index_col = False)

In [9]:
jul2019 = pd.read_csv(os.path.join(path, '7-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\3300907035.py:1: DtypeWarning: Columns (11,13,57,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  jul2019 = pd.read_csv(os.path.join(path, '7-2019.csv'), index_col = False)

In [10]:
aug2019 = pd.read_csv(os.path.join(path, '8-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\1988887576.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  aug2019 = pd.read_csv(os.path.join(path, '8-2019.csv'), index_col = False)

In [11]:
sep2019 = pd.read_csv(os.path.join(path, '9-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\4059631198.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  sep2019 = pd.read_csv(os.path.join(path, '9-2019.csv'), index_col = False)

In [12]:
oct2019 = pd.read_csv(os.path.join(path, '10-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\1847755736.py:1: DtypeWarning: Columns (11,13,57,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  oct2019 = pd.read_csv(os.path.join(path, '10-2019.csv'), index_col = False)

In [13]:
nov2019 = pd.read_csv(os.path.join(path, '11-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\2483459792.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93) have mixed types. Specify dtype option on import or set low_memory=False.
  nov2019 = pd.read_csv(os.path.join(path, '11-2019.csv'), index_col = False)

In [14]:
dec2019 = pd.read_csv(os.path.join(path, '12-2019.csv'), index_col = False)

C:\Users\Josh Wattay\AppData\Local\Temp\ipykernel_15388\3452124633.py:1: DtypeWarning: Columns (11,13,57,78,85,86,93,94,101) have mixed types. Specify dtype option on import or set low_memory=False.
  dec2019 = pd.read_csv(os.path.join(path, '12-2019.csv'), index_col = False)

In [15]:
frames = [jan2019, feb2019, mar2019, apr2019, may2019, jun2019, jul2019, aug2019, sep2019, oct2019, nov2019, dec2019]

In [16]:
frames

[        Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2019        1      1           4          5  2019-01-04
 1       2019        1      1           4          5  2019-01-04
 2       2019        1      1           4          5  2019-01-04
 3       2019        1      1           4          5  2019-01-04
 4       2019        1      1           4          5  2019-01-04
 ...      ...      ...    ...         ...        ...         ...
 638644  2019        1      1          23          3  2019-01-23
 638645  2019        1      1          24          4  2019-01-24
 638646  2019        1      1          25          5  2019-01-25
 638647  2019        1      1          26          6  2019-01-26
 638648  2019        1      1          28          1  2019-01-28

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             UA                            UA_CODESHARE
 1                             UA                            UA_CODESHARE
 2                             UA                            UA_CODESHARE
 3                             UA                            UA_CODESHARE
 4                             UA                            UA_CODESHARE
 ...                          ...                                     ...
 638644                        UA                            UA_CODESHARE
 638645                        UA                            UA_CODESHARE
 638646                        UA                            UA_CODESHARE
 638647                        UA                            UA_CODESHARE
 638648                        UA                            UA_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19977                          UA  ...
 1                          19977                          UA  ...
 2                          19977                          UA  ...
 3                          19977                          UA  ...
 4                          19977                          UA  ...
 ...                          ...                         ...  ...
 638644                     19977                          UA  ...
 638645                     19977                          UA  ...
 638646                     19977                          UA  ...
 638647                     19977                          UA  ...
 638648                     19977                          UA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 638644          NaN           NaN               NaN          NaN
 638645          NaN           NaN               NaN          NaN
 638646          NaN           NaN               NaN          NaN
 638647          NaN           NaN               NaN          NaN
 638648          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 638644             NaN              NaN            NaN         NaN         N
 638645             NaN              NaN            NaN         NaN         N
 638646             NaN              NaN            NaN         NaN         N
 638647             NaN              NaN            NaN         NaN         N
 638648             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 638644           NaN
 638645           NaN
 638646           NaN
 638647           NaN
 638648           NaN

 [638649 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2019        1      2           1          5  2019-02-01
 1       2019        1      2           2          6  2019-02-02
 2       2019        1      2           3          7  2019-02-03
 3       2019        1      2           4          1  2019-02-04
 4       2019        1      2           5          2  2019-02-05
 ...      ...      ...    ...         ...        ...         ...
 582961  2019        1      2          22          5  2019-02-22
 582962  2019        1      2          25          1  2019-02-25
 582963  2019        1      2          26          2  2019-02-26
 582964  2019        1      2          27          3  2019-02-27
 582965  2019        1      2          28          4  2019-02-28

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             AA                            AA_CODESHARE
 1                             AA                            AA_CODESHARE
 2                             AA                            AA_CODESHARE
 3                             AA                            AA_CODESHARE
 4                             AA                            AA_CODESHARE
 ...                          ...                                     ...
 582961                        DL                            DL_CODESHARE
 582962                        DL                            DL_CODESHARE
 582963                        DL                            DL_CODESHARE
 582964                        DL                            DL_CODESHARE
 582965                        DL                            DL_CODESHARE

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19805                          AA  ...
 1                          19805                          AA  ...
 2                          19805                          AA  ...
 3                          19805                          AA  ...
 4                          19805                          AA  ...
 ...                          ...                         ...  ...
 582961                     19790                          DL  ...
 582962                     19790                          DL  ...
 582963                     19790                          DL  ...
 582964                     19790                          DL  ...
 582965                     19790                          DL  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 582961          NaN           NaN               NaN          NaN
 582962          NaN           NaN               NaN          NaN
 582963          NaN           NaN               NaN          NaN
 582964          NaN           NaN               NaN          NaN
 582965          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 582961             NaN              NaN            NaN         NaN         N
 582962             NaN              NaN            NaN         NaN         N
 582963             NaN              NaN            NaN         NaN         N
 582964             NaN              NaN            NaN         NaN         N
 582965             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 582961           NaN
 582962           NaN
 582963           NaN
 582964           NaN
 582965           NaN

 [582966 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2019        1      3          30          6  2019-03-30
 1       2019        1      3          31          7  2019-03-31
 2       2019        1      3           1          5  2019-03-01
 3       2019        1      3           2          6  2019-03-02
 4       2019        1      3           3          7  2019-03-03
 ...      ...      ...    ...         ...        ...         ...
 689216  2019        1      3          25          1  2019-03-25
 689217  2019        1      3          26          2  2019-03-26
 689218  2019        1      3          27          3  2019-03-27
 689219  2019        1      3          28          4  2019-03-28
 689220  2019        1      3          29          5  2019-03-29

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             AA                                      AA
 1                             AA                                      AA
 2                             AA                                      AA
 3                             AA                                      AA
 4                             AA                                      AA
 ...                          ...                                     ...
 689216                        AA                                      AA
 689217                        AA                                      AA
 689218                        AA                                      AA
 689219                        AA                                      AA
 689220                        AA                                      AA

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19805                          AA  ...
 1                          19805                          AA  ...
 2                          19805                          AA  ...
 3                          19805                          AA  ...
 4                          19805                          AA  ...
 ...                          ...                         ...  ...
 689216                     19805                          AA  ...
 689217                     19805                          AA  ...
 689218                     19805                          AA  ...
 689219                     19805                          AA  ...
 689220                     19805                          AA  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 689216          NaN           NaN               NaN          NaN
 689217          NaN           NaN               NaN          NaN
 689218          NaN           NaN               NaN          NaN
 689219          NaN           NaN               NaN          NaN
 689220          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 689216             NaN              NaN            NaN         NaN         N
 689217             NaN              NaN            NaN         NaN         N
 689218             NaN              NaN            NaN         NaN         N
 689219             NaN              NaN            NaN         NaN         N
 689220             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 689216           NaN
 689217           NaN
 689218           NaN
 689219           NaN
 689220           NaN

 [689221 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2019        2      4           1          1  2019-04-01
 1       2019        2      4           2          2  2019-04-02
 2       2019        2      4           3          3  2019-04-03
 3       2019        2      4           4          4  2019-04-04
 4       2019        2      4           5          5  2019-04-05
 ...      ...      ...    ...         ...        ...         ...
 668254  2019        2      4          30          2  2019-04-30
 668255  2019        2      4          30          2  2019-04-30
 668256  2019        2      4          30          2  2019-04-30
 668257  2019        2      4          30          2  2019-04-30
 668258  2019        2      4          30          2  2019-04-30

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             AA                            AA_CODESHARE
 1                             AA                            AA_CODESHARE
 2                             AA                            AA_CODESHARE
 3                             AA                            AA_CODESHARE
 4                             AA                            AA_CODESHARE
 ...                          ...                                     ...
 668254                        F9                                      F9
 668255                        F9                                      F9
 668256                        F9                                      F9
 668257                        F9                                      F9
 668258                        F9                                      F9

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19805                          AA  ...
 1                          19805                          AA  ...
 2                          19805                          AA  ...
 3                          19805                          AA  ...
 4                          19805                          AA  ...
 ...                          ...                         ...  ...
 668254                     20436                          F9  ...
 668255                     20436                          F9  ...
 668256                     20436                          F9  ...
 668257                     20436                          F9  ...
 668258                     20436                          F9  ...

         Div5Airport Div5AirportID  Div5AirportSeqID Div5WheelsOn  \
 0               NaN           NaN               NaN          NaN
 1               NaN           NaN               NaN          NaN
 2               NaN           NaN               NaN          NaN
 3               NaN           NaN               NaN          NaN
 4               NaN           NaN               NaN          NaN
 ...             ...           ...               ...          ...
 668254          NaN           NaN               NaN          NaN
 668255          NaN           NaN               NaN          NaN
 668256          NaN           NaN               NaN          NaN
 668257          NaN           NaN               NaN          NaN
 668258          NaN           NaN               NaN          NaN

         Div5TotalGTime Div5LongestGTime  Div5WheelsOff Div5TailNum Duplicate  \
 0                  NaN              NaN            NaN         NaN         N
 1                  NaN              NaN            NaN         NaN         N
 2                  NaN              NaN            NaN         NaN         N
 3                  NaN              NaN            NaN         NaN         N
 4                  NaN              NaN            NaN         NaN         N
 ...                ...              ...            ...         ...       ...
 668254             NaN              NaN            NaN         NaN         N
 668255             NaN              NaN            NaN         NaN         N
 668256             NaN              NaN            NaN         NaN         N
 668257             NaN              NaN            NaN         NaN         N
 668258             NaN              NaN            NaN         NaN         N

         Unnamed: 119
 0                NaN
 1                NaN
 2                NaN
 3                NaN
 4                NaN
 ...              ...
 668254           NaN
 668255           NaN
 668256           NaN
 668257           NaN
 668258           NaN

 [668259 rows x 120 columns],
         Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
 0       2019        2      5          11          6  2019-05-11
 1       2019        2      5          11          6  2019-05-11
 2       2019        2      5          11          6  2019-05-11
 3       2019        2      5          11          6  2019-05-11
 4       2019        2      5          11          6  2019-05-11
 ...      ...      ...    ...         ...        ...         ...
 694306  2019        2      5          27          1  2019-05-27
 694307  2019        2      5          28          2  2019-05-28
 694308  2019        2      5          29          3  2019-05-29
 694309  2019        2      5          30          4  2019-05-30
 694310  2019        2      5          31          5  2019-05-31

        Marketing_Airline_Network Operated_or_Branded_Code_Share_Partners  \
 0                             DL                            DL_CODESHARE
 1                             DL                            DL_CODESHARE
 2                             DL                            DL_CODESHARE
 3                             DL                            DL_CODESHARE
 4                             DL                            DL_CODESHARE
 ...                          ...                                     ...
 694306                        NK                                      NK
 694307                        NK                                      NK
 694308                        NK                                      NK
 694309                        NK                                      NK
 694310                        NK                                      NK

         DOT_ID_Marketing_Airline IATA_Code_Marketing_Airline  ...  \
 0                          19790                          DL  ...
 1                          19790                          DL  ...

In [17]:
type(frames)

list

In [18]:
#Concatinate the Dataframes using Default Options

flights2019 = pd.concat(frames)

In [20]:
flights2019.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
0,2019,1,1,4,5,2019-01-04,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,2019,1,1,4,5,2019-01-04,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,2019,1,1,4,5,2019-01-04,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,2019,1,1,4,5,2019-01-04,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,2019,1,1,4,5,2019-01-04,UA,UA_CODESHARE,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [21]:
flights2019.columns

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       ...
       'Div5Airport', 'Div5AirportID', 'Div5AirportSeqID', 'Div5WheelsOn',
       'Div5TotalGTime', 'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum',
       'Duplicate', 'Unnamed: 119'],
      dtype='object', length=120)

In [22]:
flights2019 = flights2019.drop(columns=[
    'Operated_or_Branded_Code_Share_Partners', 
    'Originally_Scheduled_Code_Share_Airline', 
    'DOT_ID_Originally_Scheduled_Code_Share_Airline',
    'Flight_Num_Originally_Scheduled_Code_Share_Airline',
    'OriginWac', 'DestWac', 'DivAirportLandings', 'DivReachedDest',
    'DivActualElapsedTime', 'DivArrDelay', 
    'Div1Airport', 'Div1AirportID',
    'Div1AirportSeqID', 'Div1WheelsOn', 'Div1TotalGTime', 
    'Div1LongestGTime', 'Div1WheelsOff', 'Div1TailNum',
    'Div2Airport', 'Div2AirportID',
    'Div2AirportSeqID', 'Div2WheelsOn', 'Div2TotalGTime', 
    'Div2LongestGTime', 'Div2WheelsOff', 'Div2TailNum',
    'Div3Airport', 'Div3AirportID',
    'Div3AirportSeqID', 'Div3WheelsOn', 'Div3TotalGTime', 
    'Div3LongestGTime', 'Div3WheelsOff', 'Div3TailNum',
    'Div4Airport', 'Div4AirportID',
    'Div4AirportSeqID', 'Div4WheelsOn', 'Div4TotalGTime', 
    'Div4LongestGTime', 'Div4WheelsOff', 'Div4TailNum',
    'Div5Airport', 'Div5AirportID',
    'Div5AirportSeqID', 'Div5WheelsOn', 'Div5TotalGTime', 
    'Div5LongestGTime', 'Div5WheelsOff', 'Div5TailNum', 'Unnamed: 119'])

In [23]:
flights2019.shape

(8091684, 69)

In [24]:
flights2019.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,...,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivDistance,Duplicate
0,2019,1,1,4,5,2019-01-04,UA,19977,UA,5657,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,2019,1,1,4,5,2019-01-04,UA,19977,UA,5658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,2019,1,1,4,5,2019-01-04,UA,19977,UA,5658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,2019,1,1,4,5,2019-01-04,UA,19977,UA,5659,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
4,2019,1,1,4,5,2019-01-04,UA,19977,UA,5660,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N

In [25]:
flights2019.to_csv(os.path.join(path, 'flights2019.csv'))